<?php echo $this->assets->outputInlineCss(); ?>
<header class="jumbotron subhead" id="overview">
    <div class="hero-unit">
        <h1>Welcome!</h1>
        <p class="lead">This is a website secured by Phalcon Framework</p>
    </div>
</header>
<div class="page-header">
    <h1>Congratulations!</h1>
</div>

<p>You're now flying with Phalcon. Great things are about to happen!</p>

<p>This page is located at <code>views/index/index.phtml</code></p>
<p><?= $title ?></p>
<p><?php echo $t->_('hi-name', ['name' => $name]); ?><br/>
    <?php echo $t->_('song', ['song' => $song]); ?></p>

<?php echo Phalcon\Tag::form(array('categories/create', 'autocomplete' => 'off', 'method' => 'GET')) ?>
<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
<table width="100%">
    <tr>
        <td align="left">
            <?php echo Phalcon\Tag::linkTo(array('categories', 'Go Back', 'class' => 'btn')) ?>
        </td>
        <td align="right">
            <?php echo Phalcon\Tag::submitButton(array('Save', 'class' => 'btn')) ?>
        </td>
    <tr>
</table>

<div align="center">
    <h1>Create categories</h1>
</div>

<table align="center">
    <tr>
        <td align="right">
            <label for="name">Full name</label>
        </td>
        <td align="left">
            <?php echo Phalcon\Tag::textField(array('fullname', 'size' => 30)) ?>
        </td>
    </tr>

    <tr>
        <td align="right">
            <label for="slug">Slug</label>
        </td>
        <td align="left">
            <?php echo Phalcon\Tag::textField(array('slug', 'maxlength' => 30)) ?>
        </td>
    </tr>
</table>
</form>